#ifndef ERREURS_H_
#define ERREURS_H_

typedef enum TypError{
	
	GRAPHE_EXISTANT = 1,
	COMMANDE_FAITE = 2,
	ERREUR_MEMOIRE = 3,
	GRAPHE_INEXISTANT = 4,
	SOMMET_INEXISTANT = 5,
	SOMMET_INVALIDE = 6,
	SOMMET_EXISTANT = 7,
	ERREUR_ORIENTATION = 8,
	ERREUR_FICHIER = 9,
	POIDS_INVALIDE = 10,
	EST_DANS_LISTE = 11,
	ARETE_EXISTANTE = 12,
	ARETE_INEXISTANTE = 13
}TypError;


#endif
